import  Welcome  from "@/pages/Welcome";


export const metadata = {
  title: "Stock Manager",
  description: "Generated by create next app",
};

export default function Home() {
  return <Welcome />;
}
